### ISSUE TITLE
Use consistent phrasing for attacks protected against

### ISSUE THREAD

**Issue by KeithLRobertson** [theupdateframework/specification#10]
Section 1.5.2 lists the attacks which the framework is designed to prevent against, but the phrasing used switches between "Attacker does X" and "Attacker should not be able to do X".

Attacker does X:
- "Arbitrary installation attacks. An attacker installs anything they want..."
- "Fast-forward attacks. An attacker arbitrarily increases the version numbers..."
- "Vulnerability to key compromises. An attacker who is able..." (This one is particularly confusing.)
- "Wrong software installation. An attacker provides a client..."

Attacker cannot:
- "Endless data attacks. Attackers should not be able to respond..."
- "Malicious mirrors preventing updates. Repository mirrors should be unable..."
- All the others, I think.

Please pick one and stick with it. I suggest the latter ("Attacker cannot")

**Comment by vladimir-v-diaz** [comment]
@KeithLRobertson Thanks for the feedback.  We will edit the text to use consistent phrasing, and likely go with "Attacker cannot..."
