### ISSUE TITLE
Should we check for timestamp role expiration when validating a new snapshot?

### ISSUE THREAD

**Issue by erickt** [theupdateframework/specification#113]
It's possible there could be substantial amount of time between when updating the timestamp metadata, and updating a snapshot. So it's possible that at 5.2.3 the new timestamp metadata is unexpired, but it since expired by the time we start validating the new snapshot at 5.3. Does this matter? I ask because this is what rust-tuf does (see https://github.com/heartsucker/rust-tuf/blob/develop/src/tuf.rs#L223, look for all the calls to `safe_$ROLE_ref()`), and I'm trying to determine if this matters.

**Comment by joshuagl** [comment]
A [discussion in Slack](https://cloud-native.slack.com/archives/C8NMD3QJ3/p1600294344057600) about this issue suggested that we could have a fixed notion of "_now_" for the duration of the update workflow, and that we should ensure that the delta between the current time and the fixed "_now_" should not be longer than the update period of timestamp.

**Comment by rdimitrov** [comment]
@joshuagl - I think we can close this one considering #118 has been merged already 👍

**Comment by joshuagl** [comment]
Yes, thanks Radoslav. This was resolved in #118.
