### ISSUE TITLE
METAFILES object format confusion

### ISSUE THREAD

**Issue by jku** [theupdateframework/specification#134]
spec defines METAFILES object format as 
```
 { METAPATH : {
       "version" : VERSION,
       ("length" : LENGTH, |
        "hashes" : HASHES) }
   , ...
 }
```
The text makes it clear that both length and hashes are optional (and not dependent on each other) but the construct `(name:value, | name:value)` seems to imply that exactly one of these should be specified: this is how DELEGATIONS uses the same construct.

Object format should maybe be changed to
```
 { METAPATH : {
       "version" : VERSION,
       ("length" : LENGTH,)
       ("hashes" : HASHES) }
   , ...
 }
```
or is this is a misunderstanding of the definition format?

**Comment by joshuagl** [comment]
Thanks for reporting this @jku, your description matches my understanding of the spec. Would you mind submitting a patch to make the suggested change to the format for METAFILES object?

**Comment by trishankatdatadog** [comment]
Thanks @jku! I was wondering the same thing reading the spec recently. Great observation!
