### ISSUE TITLE
Clarify "paths" and "path_hash_prefixes" in delegations

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/specification#156]
In the specification [here](https://theupdateframework.github.io/specification/latest/#path_hash_prefixes), it's said:
```
In order to discuss target paths, a role MUST specify only one of the
"path_hash_prefixes" or "paths" attributes, each of which we discuss next.
```

This is confusing because it doesn't properly define which of these options is valid:
- BOTH `paths` and `path_hash_prefixes`
- ONLY ONE of `paths` and `path_hash_prefixes`
- NONE of `paths` and `path_hash_prefixes`

**Comment by joshuagl** [comment]
Thank you for filing, we can definitely work on making this clearer. A valid DELEGATIONS object can have one or none of `paths` or `path_hash_prefixes` (bullets two and three from your list).

**Comment by jku** [comment]
> valid DELEGATIONS object can have one or none of `paths` or `path_hash_prefixes` (bullets two and three from your list).

I agree this seems logical but will also point out that the current/legacy updater will currently raise an error if neither is defined.
