### ISSUE TITLE
Wish: Import academics papers from tuf project

### ISSUE THREAD

**Issue by rzr** [theupdateframework/specification#159]
Those static files are not used to build software and thus may have side effects of distribution of package 
due to not appropriate licensing.
Apache-2.0 is an opensource license and sources of those PDT files are not published.
It's not a critical issue because source package can be repacked without the suspicious files,
(I've done this for debian to comply DFSG:
https://github.com/theupdateframework/tuf/issues/263#issuecomment-835239415
)
Relocating files outside tuf project will prevent this extra processing step and make the chain of trust safer.

Once files merged in heref they can removed from tuf:
https://github.com/theupdateframework/tuf/pull/1380

My PR will import gits changes from tuf to preserve attributions.

**Comment by joshuagl** [comment]
As discussed elsewhere, the published academic papers (PDF) are hosted on the website and don't belong here.
