### ISSUE TITLE
Clarify consequence of a delegated-to role not being found during target validation

### ISSUE THREAD

**Issue by awwad** [theupdateframework/specification#17]
## Summary
The spec is not adequately clear on what a client should do when traversing a list of delegations if it cannot obtain and validate a role specified in that list. As a consequence, different clients may have different delegation order semantics -- intentionally or unintentionally.

## Background
Near the bottom of section 4.5 [in the spec](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#4-document-formats) is an explanation of delegation prioritization.

## Details
Scenario:
Suppose some role "T" makes a non-terminating delegation of target files matching `some_path/*` to some roles "R1" and "R2", in that order.
_(Note that the question is moot for a terminating delegation. "Terminating" is defined in the spec, but in short: if T makes a terminating delegation of namespace some_path/\* to R1, then if the search for a target that matches some_path/\* reaches the delegation to R1, it will not backtrack to proceed to R2 or further delegations in T's list of delegations. In other words, by making a terminating delegation of some_path/\* to R1, T is excluding from its later delegations the right to specify a target that matches some_path/\*)_

**Early delegation confers early right to specify a target. It is clear that if R1 specifies target info and a client finds a matching target file, that this should be considered the valid target file, and any target info R2 provides for this target should be disregarded.** But what if a client can't find or validate an R1 role file? Should the client proceed to R2?

## Solution
**The behavior we think makes the most sense, to provide for a consistent meaning for delegations and prevent MITM attacks that exclude particular role files resulting in different targets being deemed valid, has the client halt its search for target file info for the given target if it cannot obtain or validate R1, and not proceed to R2 or backtrack, since R1 has the right to specify the target info for that target.** This also is the behavior of the reference implementation.

The spec should indicate that this is the expected behavior, in [spec section 5.1 (Detailed client workflows)](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#5-detailed-workflows).

If this is not made rigid, it should at least be made clear that delegation order semantics will vary based on the behavior chosen. (People should not stumble into a behavior.)

**Comment by awwad** [comment]
FWIW, here's a script you can use to play with this behavior and similar behaviors using the current code in the reference implementation. It'll set up a fresh repository and fresh client, perform delegations equivalent to those described above, and attempt to get the target info for a target. Run it in an interactive shell (python -i <script_name>) and you can move role files in and out of place and see what happens if you like.

```Python
import tuf
import tuf.repository_tool as rt
import tuf.client.updater as updater
import tuf.settings

import os, subprocess, time, shutil, atexit

reponame = 'temp_repo'
client_dir = 'temp_client'
target_fname_in_repo = os.path.join(reponame, 'targets', 'a1.txt')


rt.generate_and_write_rsa_keypair('keykey', 3072, 'pw')
pubkey = rt.import_rsa_publickey_from_file('keykey.pub')
prikey = rt.import_rsa_privatekey_from_file('keykey', 'pw')

repo = rt.create_new_repository(reponame)

for role in [repo.targets, repo.root, repo.timestamp, repo.snapshot]:
  role.add_verification_key(pubkey)
  role.load_signing_key(prikey)


for rolename in ['r1', 'r2']:
  repo.targets.delegate(rolename, [pubkey], ['/a*'])
  repo.targets(rolename).add_verification_key(pubkey)
  repo.targets(rolename).load_signing_key(prikey)

# Hashes are calculated from target files when we call
# repo.write (or repo.writeall), so we have to make at least
# two separate calls so that r1 and r2 can specify different
# hashes. We'll use three for ... reasons not worth explaining. 

for rolename in ['r1', 'r2']:
  with open(target_fname_in_repo, 'w') as fobj:
    fobj.write('contents according to ' + rolename)
  repo.targets(rolename).add_target(target_fname_in_repo)
  repo.write(rolename)

# Write all the top-level metadata.

repo.writeall()

# Host the repo data

SERVER_PORT = 35001
command = ['python', '../tests/simple_server.py', str(SERVER_PORT)]
server_process = subprocess.Popen(command, stderr=subprocess.PIPE, cwd=os.path.join(os.getcwd(), reponame))
atexit.register(server_process.kill)
url = 'http://localhost:'+str(SERVER_PORT)
time.sleep(0.2)


# Set up client

mirrors_dict = {'mirror1': {
    'url_prefix': url,
    'metadata_path': 'metadata.staged',
    'targets_path': 'targets',
    'confined_target_dirs': ['']}}
if os.path.exists(client_dir):
  shutil.rmtree(client_dir)
  time.sleep(0.1)

os.makedirs(os.path.join(client_dir, reponame, 'metadata', 'current'))
os.makedirs(os.path.join(client_dir, reponame, 'metadata', 'previous'))
shutil.copy(
    os.path.join(reponame, 'metadata.staged', 'root.json'),
    os.path.join(client_dir, reponame, 'metadata', 'current'))

tuf.settings.repositories_directory = client_dir
u = updater.Updater(reponame, mirrors_dict)

u.refresh()

targeting = u.get_one_valid_targetinfo('/a1.txt')
```

**Comment by vladimir-v-diaz** [comment]
What behavior does the reference implement exhibit?  Does it follow the solution proposed in this issue?  If not, should we open an issue on the reference implementation repo?

**Comment by awwad** [comment]
The reference implementation behaves correctly: if R1 is not found or if R1 cannot be validated, it aborts without looking for R2. It might merit an eyeball to make sure there aren't edge cases and make it clear that this is intended behavior in the reference implementation, but it seems to behave in a manner consistent with that recommended in this issue.
