### ISSUE TITLE
Clarify if "signatures" can be extended

### ISSUE THREAD

**Issue by MVrachev** [theupdateframework/specification#203]
The [Document formats](https://theupdateframework.github.io/specification/latest/#document-formats) section of the specification says the following:
```
All of the formats described below include the ability to add more attribute-value fields
to objects for backward-compatible format changes.
Implementers who encounter undefined attribute-value pairs in the format must include
the data when calculating hashes or verifying signatures and
must preserve the data when re-serializing.
```

This implies that the specification implementations should support unrecognized fields at each place in the **SIGNED** portion as they will be used to calculate the hashes or do signature verification.

It's a little unclear for me if unrecognized fields are allowed in the signatures dictionaries.
Any opinions?

**Comment by trishankatdatadog** [comment]
I think it should allow it, yeah. There are use cases in DSSE where you may want additional fields, but arguments remain open:

https://github.com/secure-systems-lab/dsse/issues/39

**Comment by MVrachev** [comment]
@mnm678, @asraa and @jku shared their opinions on the `python-tuf` issue https://github.com/theupdateframework/python-tuf/issues/1802.
In the [document section](https://theupdateframework.github.io/specification/latest/#document-formats) the spec currently says:
`All of the formats described below include the ability to add more attribute-value fields to objects`.
 Now when I reread this I see it's before defining any of the formats meaning it should apply to signatures as well.

I initially thought it's applicable only to the **SIGNED** fields as `undefined attribute-value pairs in the format must include the data when calculating hashes or verifying signatures`.
This doesn't mean that the sentence before that excludes `signatures` as a possible place for additional fields.

I am no longer certain there is a need for any clarification...
I think I just misread it and after a discussion with a couple of people, I realized there is noting stopping unrecognized fields inside the signatures when reading the current version of the spec (version 1.0.28).
