### ISSUE TITLE
doc: outdated maintainers list in README 

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/specification#206]
The maintainers list in the [Acknowledgement section of the main README.md](https://github.com/theupdateframework/specification#acknowledgements) is outdated. 

Sync with up-to-date [MAINTAINERS.md](https://github.com/theupdateframework/specification/blob/master/MAINTAINERS.md).

**Comment by joshuagl** [comment]
Do we want to explicitly name maintainers and their affiliation, or just provide a generic statement which links to the maintainer list?

> [Maintainers](MAINTAINERS.md) include collaborators from academia and industry.

**Comment by lukpueh** [comment]
The generic statement seems fine to me.
