### ISSUE TITLE
Verify and fix the version comparison done for metadata files

### ISSUE THREAD

**Issue by rdimitrov** [theupdateframework/specification#207]
**Description:**

- Verify the usage of “less than vs less than or equal to” done for version comparison throughout the specification
- The confusion comes that the spec uses the same text in multiple scenarios that are not the same
- Meta versions can be equal, but metadata versions probably should not be. For everything other than timestamp, it does not matter. For timestamp, spec always expects to download the latest and use that
- For example, it’s normal for the timestamp version to change but still point to the same snapshot version

**Related issues:**

- https://github.com/theupdateframework/go-tuf/issues/218

**Comment by joshuagl** [comment]
See related spec issue https://github.com/theupdateframework/specification/issues/114
