### ISSUE TITLE
'meta' is not a descriptive name in the Timestamp and Snapshot definitions

### ISSUE THREAD

**Issue by awwad** [theupdateframework/specification#27]
The spec defines Timestamp and Snapshot metadata such that the meat of their data lies in a dictionary called `meta`. This should probably be called 'roleinfo' or something along those lines, if this metadata format is ever adjusted in an equally disruptive way. (It is probably not worth changing metadata definitions just for this, but the next time they do change, this is worth considering.)

Current:
```Javascript
"_type": "snapshot",
  "spec_version": "1",
  "expires": "2030-01-01T00:00:00Z",
  "meta": {
   "root.json": {
    "version": 1
   },
   "targets.json": {
    "version": 1
   },
   "project.json": {
    "version": 1
    },
   }
  "version": 1
```

**Comment by lukpueh** [comment]
tracked in #149
