### ISSUE TITLE
Snapshot.json example is missing hash(es) and size for the root role

### ISSUE THREAD

**Issue by erickt** [theupdateframework/specification#31]
In section [4.6 of the spec](https://github.com/theupdateframework/specification/blob/99dbf9af48c9d8c3cc78ce1b8d185df10aa8c503/tuf-spec.md), the description of the snapshot.json file states:

> The snapshot.json file is signed by the snapshot role. It lists the version numbers of all metadata on the repository, excluding timestamp.json and mirrors.json. For the root role, the hash(es), size, and version number are listed.

However, the example does not include the hashes or size for the root.json file:

```
 {
 "signatures": [
  {
   "keyid": "fce9cf1cc86b0945d6a042f334026f31ed8e4ee1510218f198e8d3f191d15309",
   "sig": "f7f03b13e3f4a78a23561419fc0dd741a637e49ee671251be9f8f3fceedfc112e4
           4ee3aaff2278fad9164ab039118d4dc53f22f94900dae9a147aa4d35dcfc0f"
  }
 ],
 "signed": {
  "_type": "snapshot",
  "spec_version": "1",
  "expires": "2030-01-01T00:00:00Z",
  "meta": {
   "root.json": {
    "version": 1
   },
   "targets.json": {
    "version": 1
   },
   "project.json": {
    "version": 1
    },
   }
  "version": 1
  },
 }
```

Could they be added?

Also, I've seen mentioned in a [few places that TAP 5](https://github.com/theupdateframework/tuf/issues/451) removes the need to actually  include the root in the snapshot file, but I'm not sure if TAP 5 is integrated into the spec, or is just planned to be incorporated in some future version of TUF.

**Comment by erickt** [comment]
It looks like these values were present way back when, but was removed in https://github.com/theupdateframework/tuf/pull/466. Should this line be removed from the spec?

> For the root role, the hash(es), size, and version number are listed.

Or Perhaps rephrased to this to be backwards compatible?

> For the root role, the hash(es) and size may be listed.

**Comment by trishankatdatadog** [comment]
@erickt The complication is that it is actually permissible to list hashes (if not sizes) for all metadata files (other than the timestamp, which is never listed) in the snapshot. See Section 5.6 of the [Mercury](https://www.usenix.org/system/files/conference/atc17/atc17-kuppusamy.pdf) paper. It's just that the reference implementation hasn't implemented it yet.

**Comment by erickt** [comment]
@trishankatdatadog Yeah that sounds like a reasonable defense. Would it be reasonable to extend the example for snapshot.json to add a delegation that lists the hash(es) and size in order to encourage clients to consume them if they are available?

**Comment by trishankatdatadog** [comment]
@erickt, yes, please. In fact, we should not even list `root.json` (just like `timestamp.json`) in `snapshot.json` anymore. Right @JustinCappos ?

**Comment by JustinCappos** [comment]
Yes, this is correct.  root.json should not be listed.

**Comment by lukpueh** [comment]
I just noticed that [docs/METADATA.md](https://github.com/theupdateframework/tuf/blame/v0.11.2.dev3/docs/METADATA.md#L67) also carries misleading (outdated) information in that regard. There is no mention of version numbers, or exclusion of `root.json` but instead it says:
> The snapshot.json metadata file lists hashes and sizes of all metadata files other than timestamp.json


Btw. all sample `snapshot.json` files in the reference implementation also [list `root.json`](https://github.com/theupdateframework/tuf/search?q=filename%3Asnapshot.json+%22root.json%22&unscoped_q=filename%3Asnapshot.json+%22root.json%22).
