### ISSUE TITLE
Does timestamp.json still require `length` and `hashes`?

### ISSUE THREAD

**Issue by erickt** [theupdateframework/specification#38]
In 4.6 of the spec, the timestamp role METAFILES is described as:

> METAFILES is the same is described for the snapshot.json file. In the case of the timestamp.json file, this will commonly only include a description of the snapshot.json file.

Where the METAFILES described in snapshot.json is:

```
METAFILES is an object whose format is the following:

 { METAPATH : {
       "version" : VERSION }
   , ...
 }
METAPATH is the metadata file's path on the repository relative to the metadata base URL.

VERSION is listed for the root file and all other roles available on the repository.
```

However, the example in the spec includes the `size` and `hashes` field:

```
...
 "signed": {
  "_type": "timestamp",
  "spec_version": "1",
  "expires": "2030-01-01T00:00:00Z",
  "meta": {
   "snapshot.json": {
    "hashes": {
     "sha256": "c14aeb4ac9f4a8fc0d83d12482b9197452f6adf3eb710e3b1e2b79e8d14cb681"
    },
    "length": 1007,
    "version": 1
   }
...
```

Are the `length` and `hashes` field optional for the timestamp.json role, or are they required? I'm not sure if the arguments made in https://github.com/theupdateframework/tuf/issues/451 and https://github.com/theupdateframework/tuf/issues/465 to make these fields optional for the snapshot role also apply to the timestamp role.

**Comment by trishankatdatadog** [comment]
Since `timestamp.json` is always constant size in practice (but even if attackers inflate the file, we have upper bounds on downloading files in practice), this is not a problem. It would be appreciated if you could send a PR clarifying this :)

**Comment by awwad** [comment]
As to Eric's question about the hashes:

The TUF specification is currently written to require that timestamp list hashes for snapshot, yes; this is explicit in 2.1.4 in the spec.

I cannot now think of a reason that the hash of snapshot in timestamp (instead of just the version of snapshot in timestamp) is really that helpful.  I may be forgetting something.  Anyone else?
