### ISSUE TITLE
Preserve history?

### ISSUE THREAD

**Issue by trishankatdatadog** [theupdateframework/specification#5]
It's not a big deal, but it's too bad we lost a lot of git history in moving the specification to a new repository.

**Comment by vladimir-v-diaz** [comment]
No need for despair.  The original specification and its full git history was [preserved](https://github.com/theupdateframework/tuf/blob/develop/docs/tuf-spec.txt).

The text of the original file was edited to note the specification's new home (this repository).

Cheers!

**Comment by vladimir-v-diaz** [comment]
Should we provide a link to the original file?  I wonder if others are also interested in the specifications git history.

**Comment by trishankatdatadog** [comment]
Hey @vladimir-v-diaz, long time!

I understand the history is there in the old repository, but it would have been nice to [preserve it in the new one](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/).

Oh, well, maybe next time :)

**Comment by awwad** [comment]
👍  I agree w/ Trishank: almost always worth transferring history. It takes a little bit of tinkering, but it's not too bad.

At this point, it could still be worth doing it (rebuilding the master branch locally in a new splitting of the old repo, cherry-picking the 23 commits that are currently in this repo, and then force pushing the new branch to recover the full history), but perhaps not. There seem to be enough people following the new one already that it might be disruptive. I'm not sure.

**Comment by trishankatdatadog** [comment]
yeah, it's a little sad that the complete history of the specification has not been preserved, because lots of people worked on it. oh, well.
