### ISSUE TITLE
Clarify the type of the target "custom" field

### ISSUE THREAD

**Issue by erickt** [theupdateframework/specification#50]
In 4.5 of the spec, the `TARGETPATH` is defined as:

```
 { TARGETPATH : {
       "length" : LENGTH,
       "hashes" : HASHES,
       ("custom" : { ... }) }
   , ...
 }
```

with custom being defined as:

> If defined, the elements and values of "custom" will be made available to the client application. The information in "custom" is opaque to the framework and can include version numbers, dependencies, requirements, and any other data that the application wants to include to describe the file at TARGETPATH. The application may use this information to guide download decisions.

Just to be safe, is `custom` a json object (as the snippet suggests), or is it allowed to be any json value? As best as I can tell, python-tuf asserts it's an [object](https://github.com/theupdateframework/tuf/blob/4f01a31346c2da9c0fb79a62cd6bb77da48ba5ed/tuf/formats.py#L231). If this the case, I'll submit a patch to make the spec more explicit.

**Comment by trishankatdatadog** [comment]
I think we should clarify that it's an object, so that different applications can safely consume different parts of it w/o overlapping with each other. Thanks for raising this!
