### ISSUE TITLE
Ambiguity between section 5.1.3 and 6.1 regarding updating root keys

### ISSUE THREAD

**Issue by erickt** [theupdateframework/specification#56]
In section 5.1.3, the spec states:

> 1.3. Check signatures. Version N+1 of the root metadata file MUST have been signed by: (1) a threshold of keys specified in the trusted root metadata file (version N), and (2) a threshold of keys specified in the new root metadata file being validated (version N+1). If version N+1 is not signed as required, discard it, abort the update cycle, and report the signature failure. On the next update cycle, begin at step 0 and version N of the root metadata file.

However, this seems inconsistent with section 6.1 when speaking about recovering from a compromised root key:

> To replace a compromised root key or any other top-level role key, the root role signs a new root.json file that lists the updated trusted keys for the role. When replacing root keys, an application will sign the new root.json file with both the new and old root keys. Any time such a change is required, the root.json file is versioned and accessible by version number, e.g., 3.root.json. Clients update the set of trusted root keys by requesting the current root.json and all previous root.json versions, until one is found that has been signed by a threshold of keys that the client already trusts. This is to ensure that outdated clients remain able to update, without requiring all previous root keys to be kept to sign new root.json metadata.

As best as I can tell, 5.1 suggests that you update the root metadata from N, to N+1, N+2, to N+M etc. But 6.1 looks like it says you figure out the latest root version, and walk backwards from N+M, N+M-1, N+M-2, etc until you find a root metadata that's been signed by a quorum of keys trusted by the version N metadata.

In this case, it seems like we could have clients with different strategies could end up trusting different roots. For example:

* create a keys (K1) and sign root (R1) with them.
* roll the root metadata (R2) with new keys (K2) and sign the metadata with K1 and K2.
* we decide (R2) was compromised, so we generate (R3) and sign metadata with K1 and K3.

So a client thats updating from R1 with the forward updating updates to R2, and it will refuse to update to R3 because K2 didn't sign R3, but a client using the backwards strategy at R1 would skip R2 because R3 was signed by K1.

Looking at [python-tuf](https://github.com/theupdateframework/tuf/blob/develop/tuf/client/updater.py#L1105)  implements the forward strategy. Is that the correct approach? If so, could section 6.1 be updated to reflect this?

**Comment by trishankatdatadog** [comment]
Eric, thanks for reporting this issue, and yes, it's certainly a discrepancy.

To me, it makes no sense to work backwards, because: (1) you should not trust the version number of the "latest" one w/o verifying it, and (2) more seriously, there need not be any overlap of keys whatsoever between this "latest" version and your current one on disk.

Therefore, I vote that we should specify and use only the forwards strategy. Does anyone have objections?

**Comment by JustinCappos** [comment]
Consistency is the most important thing here.  I agree we should use the
forward verification strategy.

**Comment by lukpueh** [comment]
I agree to use the forward strategy. @trishankatdatadog and I only just recently revised this in the reference implementation (see [tuf#885](https://github.com/theupdateframework/tuf/pull/885) and [tuf#930](https://github.com/theupdateframework/tuf/pull/930)).

Also, while updating the parts about key rotation, would it make sense to move them to a new "Server/Repository" subsection of  "5. Detailed Workflows"? I find it a bit lost under "6. Usage". 

On a more general note, I think, implementers would benefit to get the same level of detail for the server side workflows, as we already provide for the client side. Or was this left out of the spec on purpose?

**Comment by lukpueh** [comment]
@erickt, please let me know if you think that https://github.com/theupdateframework/specification/issues/56 resolves the ambiguity.

**Comment by lukpueh** [comment]
We can address [my suggestions above](https://github.com/theupdateframework/specification/issues/56#issuecomment-545879347), i.e. add detailed workflow section for a tuf repository,  in a separate PR.  If others think it's worthwhile, I can create an issue.

*Such an  issue will probably suggest to explain in the spec how metadata is interdependent, and how, on a tuf server, the update of one role metadata, requires the update of other role metadata. See https://github.com/theupdateframework/tuf/issues/958#issuecomment-553830755 for more details.*
