### ISSUE TITLE
Can delegated targets public keys be found in the root metadata?

### ISSUE THREAD

**Issue by erickt** [theupdateframework/specification#58]
In section [4.4.5](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#4-document-formats), is it allowed for TUF clients to find the public keys in the root metadata, or is it required that the keys only be found in the targets (or delegated targets) metadata?

**Comment by trishankatdatadog** [comment]
Only the keys for the top-level roles (`root`, `timestamp`, `snapshot`, and `targets`) are to be trusted from the ` root` role metadata. The rest of the keys come from `targets` and delegated friends.

Does this answer your question, Eric? Also, what is the context here, please?

**Comment by erickt** [comment]
@trishankatdatadog Thanks! This came from rust-tuf's implementation of resolving a key id to a public key structure. I wanted to see if we should be incorporating the keys listed in the `root` metadata when trying to find a key. I wasn't sure what we should do if some delegated `foo` role was signed with a `root` metadata key, but the key wasn't listed in the `targets` other intermediate delegated metadata. It sounds like this should be treated as an error, rather than accepting the metadata has a valid signature.

**Comment by trishankatdatadog** [comment]
Yeah, it definitely sounds like an error to me.

Ideally, the keys used to verify a metadata file should be scoped. What I mean is that there shouldn't internally be a global map of keys. So even if the root metadata file and some other delegated targets metadata file shared the same keyids, it really shouldn't matter. All top-level role metadata should be scoped to trust only pubkeys from the root metadata, and any delegated targets role metadata should be scoped to trust only pubkeys from the originating delegation in the graph being traversed.

Does this make sense?

**Comment by lukpueh** [comment]
IMO the spec makes it quite clear that the keys in root.json are for the top-level roles.  However, it never mentions explicitly where keys for delegated targets roles are defined.

I have a pending PR that adopts the TAP 3 (multi-role delegation) metadata format, where I describe the [keys field of a delegating targets role](https://github.com/theupdateframework/specification/pull/57/files#diff-94b2d37a08c587082c1ea1aaead6f973R828-R831).  @erickt do you think that is sufficient to close this issue? 

Alternatively/Additionally, we could add a sentence to [*3.1.2.1 Metadata files for targets delegation*](https://github.com/theupdateframework/specification/blame/0cddec0a60f95f06d2e23ebadbd876eeb62c1df3/tuf-spec.md#L448-L453), that makes it clear that delegated target roles are authorized by the keys listed in the directly delegating target role.

**Comment by erickt** [comment]
@lukpueh Adding a sentence to 3.1.2.1 would be helpful. It might be a little redundant with your TAP 3, but I don't think it hurts to re-state how this should work. I can whip up a sentence for consideration. Thanks!
