### ISSUE TITLE
Should timestamp metadata be written to non-volatile storage?

### ISSUE THREAD

**Issue by erickt** [theupdateframework/specification#68]
I noticed that [section 5.2 of the spec](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#5-detailed-workflows) does not specify if the client should persist the timestamp metadata to non-volatile storage:

> 2. Download the timestamp metadata file, up to Y number of bytes (because the size is unknown.) The value for Y is set by the authors of the application using TUF. For example, Y may be tens of kilobytes. The filename used to download the timestamp metadata file is of the fixed form FILENAME.EXT (e.g., timestamp.json).

In comparison, root, snapshot, and targets roles explicitly mention that the client should write the metadata to non-volatile storage. For example:

> 3. Download snapshot metadata file, up to the number of bytes specified in the timestamp metadata file. If consistent snapshots are not used (see Section 7), then the filename used to download the snapshot metadata file is of the fixed form FILENAME.EXT (e.g., snapshot.json). Otherwise, the filename is of the form VERSION_NUMBER.FILENAME.EXT (e.g., 42.snapshot.json), where VERSION_NUMBER is the version number of the snapshot metadata file listed in the timestamp metadata file. In either case, the client MUST write the file to non-volatile storage as FILENAME.EXT.

Was this intentional, or was this an oversight? As best as I can tell, all the implementations write the timestamp metadata to disk before downloading the rest of the metadata.

**Comment by JustinCappos** [comment]
This was an oversight.  It should be written to non-volatile storage.  

Thanks for catching this!  Would you like to send a PR and we'll merge?

**Comment by erickt** [comment]
Thanks! I just pushed a PR with a fix for this in https://github.com/theupdateframework/specification/pull/70.
