### ISSUE TITLE
Link broken in tuf_spec

### ISSUE THREAD

**Issue by florianeichin** [theupdateframework/specification#7]
The Link to the submitted Mercury draft in Detailed Workflow 1.9 in the tuf_spec is broken.
it points to this link, but that is not available anymore.
https://ssl.engineering.nyu.edu/papers/kuppusamy_usenix_17.pdf

Is it maybe that link now:
https://ssl.engineering.nyu.edu/papers/kuppusamy-mercury-usenix-2017.pdf

**Comment by vladimir-v-diaz** [comment]
@florianeichin 
Thanks for reporting the issue!
