### ISSUE TITLE
Need formal specification of TUF

### ISSUE THREAD

**Issue by trishankkarthik** [theupdateframework/specification#75]
The [current specification](https://github.com/theupdateframework/tuf/blob/5f94d5be0d9c2140e440a7076c6ccfa6263864dd/docs/tuf-spec.txt) is too informal: it leaves many details unspecified (e.g. the exact algorithmic flow of a conformant updater, exactly what hashed delegations or consistent snapshots are, etc.).

Ideally, the TUF specification would be much more formal. (We should look into a suitable language.)

We should also unify our many different names for the same thing (e.g. 'consistent snapshots' == 'hashed snapshot trees', 'lazy bin walk' == 'hashed delegations', 'release' == 'snapshot'), and produce a standard glossary.

**Comment by JustinCappos** [comment]
I'd also flag uses of the term 'rotate' as a specific concern, especially with TAP 8 looming.  We need to be very precise about what is meant.
