### ISSUE TITLE
Enforce release tags on merges into master (i.e. release bumps)

### ISSUE THREAD

**Issue by lukpueh** [theupdateframework/specification#95]
#87 added versioning/release policies, plus a script that helps to enforce them. One of the policies is:
> Merges with 'master' must be followed by a git tag for the new version number.

This policy is not enforced by the script, as the script is auto-executed on PRs, but this policy would need to be enforced post-merge.

It would be nice to either:
- auto-tag on merge into master ( see https://github.com/theupdateframework/specification/pull/87#discussion_r374693542), or
- otherwise insistently remind the maintainer to tag the release

**Comment by joshuagl** [comment]
I really like the idea of auto-tag on merge to master, we could use something like this GitHub Action to enable that workflow https://github.com/marketplace/actions/automatic-releases

**Comment by trishankatdatadog** [comment]
The Agent integrations [workflows](https://github.com/DataDog/integrations-core/tree/master/.github/workflows) might be helpful to read, too...

Cc @ofek

**Comment by lukpueh** [comment]
> otherwise insistently remind the maintainer to tag the release

We could have the release policy checker script on Travis post [these lines](https://travis-ci.org/github/theupdateframework/specification/builds/693838175#L186-L187) as a [comment using the GitHub API](https://developer.github.com/v3/issues/comments/#create-a-comment).

Might be a fun self-contained task for a student (cc @SantiagoTorres, @adityasaky)

**Comment by joshuagl** [comment]
We did this in https://github.com/theupdateframework/specification/pull/148
