### ISSUE TITLE
updateframework.com SSL Cert Issue

### ISSUE THREAD

**Issue by highb** [theupdateframework/specification#97]
It looks like https://updateframework.com has an invalid cert that doesn't match the domain. I'm not sure how much you care about that old domain, but it is linked from this discussion thread on securing RubyGems with TUF. That's how I found it. https://groups.google.com/forum/#!msg/rubygems-developers/lnnGTlfsuYo/TLDcJ2RPSDoJ

**Comment by trishankatdatadog** [comment]
Good catch, thanks, Brandon!

Could we use a domain provider that automatically takes care of this for us?

**Comment by JustinCappos** [comment]
I'll get our IT staff on this.

**Comment by lukpueh** [comment]
Looks like this has been resolved. Thanks!
