### ISSUE TITLE
key object definition is missing keyid_hash_algorithms

### ISSUE THREAD

**Issue by jku** [theupdateframework/specification#99]
spec says that all keys have the format
```
  { "keytype" : KEYTYPE,
    "scheme" : SCHEME,
    "keyval" : KEYVAL
  }
```
this matches the specific key format descriptions and later the examples.

The implementation at the moment looks like this however:
```
  { "keyid_hash_algorithms" : [ HASH_ALGORITHM, ... ] 
    "keytype" : KEYTYPE,
    "scheme" : SCHEME,
    "keyval" : KEYVAL
  }
```
where HASH_ALGORITHM is e.g. "sha256","sha512"

**Comment by lukpueh** [comment]
Thanks for submitting the issue, @jku! This discrepancy is being discussed in detail in https://github.com/theupdateframework/tuf/issues/848. 

Please also take a look at [TAP 12](https://github.com/theupdateframework/taps/blob/master/tap12.md) (draft), which proposes a new way of dealing with keyids.

**Comment by joshuagl** [comment]
I'm closing this issue as `keyid_hash_algorithms` is explicitly not part of the spec.
